### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by dhunganaanish** [charkster/keysight_33600a#1]
File "C:\Users\aanis\OneDrive\Documents\python\frequency sweep\keysight_33600a.py", line 165
    "OUTPut1:LOAD{0}": "<ohms>|INFinity|MINimum|MAXimum|DEFault",
                     ^
SyntaxError: invalid syntax

**Comment by charkster** [comment]
Thank you @dhunganaanish . Not sure how the previous comma got removed. I just added the comma.
Fixed in https://github.com/charkster/keysight_33600a/commit/a7d56cdc2cce5ce0c5ee216d23cf3f5f30119d3e

**Comment by dhunganaanish** [comment]
I have not able to figure out how to sweep frequency using this driver code. can you help?
